### ISSUE TITLE
color-blind colors for tcolorbox as an option?

### ISSUE THREAD

**Issue by mysecondnameisdanger** [samcarter/beamertheme-tcolorbox#2]
Can we have color-blind colors for tcolorboxes as an option? 

Thanks

**Comment by samcarter** [comment]
The `tcolorbox` inner beamer theme does not influence the colours. It takes the colours from whatever beamer theme (or other settings) are in effect:

```
\documentclass{beamer}

\usecolortheme{crane}

\useinnertheme{tcolorbox}

\begin{document}

\begin{frame}
  \begin{block}{title}
  content...
  \end{block}
  
  \begin{alertblock}{title}
  content...
  \end{alertblock}
  
  \begin{exampleblock}{title}
  content...
  \end{exampleblock}
\end{frame}

\end{document}
```

So to get colorblind-friendly colours, either choose a colour theme, which you like, or tell me which colours you want to have and I can show you how to change the beamer colour theme.

If you are interested in this topic, there will be a talk about colourblind-friendly typsetting at the TUG'24 conference next week: https://tug.org/tug2024/abstracts/pfahler-colorblind.txt (there will be live stream and recordings on youtube)
